# Generated by Django 3.1.5 on 2021-01-27 08:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_list',
            fields=[
                ('market_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('cur_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_Qty', models.IntegerField()),
                ('avg_purchase_price', models.IntegerField()),
                ('stock_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.stock_list')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('cur_price', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 27, 8, 19, 20, 747786, tzinfo=utc))),
                ('purchase', models.BooleanField()),
                ('stock_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.stock_list')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_search_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.stock_list')),
            ],
        ),
    ]
