# Generated by Django 3.1.5 on 2021-01-27 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('stock_name', models.CharField(max_length=100)),
                ('cur_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_search_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.stock_list')),
            ],
        ),
    ]
