# Generated by Django 3.1.5 on 2021-01-26 02:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_list',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 26, 2, 12, 17, 683836, tzinfo=utc)),
        ),
    ]
