# Generated by Django 3.1.5 on 2021-01-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_transaction_history_user_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_result',
            name='stock_ID',
        ),
        migrations.RemoveField(
            model_name='user_result',
            name='user_ID',
        ),
        migrations.DeleteModel(
            name='Transaction_history',
        ),
        migrations.DeleteModel(
            name='User_result',
        ),
    ]
