# Generated by Django 3.1.5 on 2021-01-27 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_transaction_history_user_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 27, 4, 55, 20, 504489, tzinfo=utc)),
        ),
    ]
