# Generated by Django 3.1.4 on 2021-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
