# Generated by Django 3.1.4 on 2021-01-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210103_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='keyword',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(),
        ),
    ]
