# Generated by Django 3.1.4 on 2021-01-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
