# Generated by Django 3.1.4 on 2021-01-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='title',
            new_name='subject',
        ),
    ]
